const persons = [
  {name: "Smith",      age: "47"},
  {name: "Johnson",    age: "28"},
  {name: "Williams",   age: "34"},
  {name: "Brown",      age: "32"},
  {name: "Jones",      age: "39"},
  {name: "Miller",     age: "35"},
  {name: "Davis",      age: "8"},
  {name: "Garcia",     age: "24"},
  {name: "Rodriguez",  age: "48"},
  {name: "Wilson",     age: "37"},
  {name: "Martinez",   age: "26"},
  {name: "Anderson",   age: "31"},
  {name: "Taylor",     age: "31"},
  {name: "Thomas",     age: "34"},
  {name: "Hernandez",  age: "37"},
  {name: "Moore",      age: "30"},
  {name: "Martin",     age: "36"},
  {name: "Jackson",    age: "18"},
  {name: "Thompson",   age: "30"},
  {name: "White",      age: "50"},
  {name: "Lopez",      age: "24"},
  {name: "Lee",        age: "41"},
  {name: "Gonzalez",   age: "25"},
  {name: "Harris",     age: "16"},
  {name: "Clark",      age: "19"},
  {name: "Lewis",      age: "34"},
  {name: "Robinson",   age: "44"},
  {name: "Walker",     age: "28"},
  {name: "Perez",      age: "23"},
  {name: "Hall",       age: "25"},
  {name: "Young",      age: "50"},
  {name: "Allen",      age: "55"},
  {name: "Sanchez",    age: "55"},
  {name: "Wright",     age: "36"},
  {name: "King",       age: "32"},
  {name: "Scott",      age: "39"},
  {name: "Green",      age: "0"},
  {name: "Baker",      age: "24"},
  {name: "Adams",      age: "19"},
  {name: "Nelson",     age: "8"},
  {name: "Hill",       age: "41"},
  {name: "Ramirez",    age: "7"},
  {name: "Campbell",   age: "45"},
  {name: "Mitchell",   age: "13"},
  {name: "Roberts",    age: "34"},
  {name: "Carter",     age: "43"},
  {name: "Phillips",   age: "39"},
  {name: "Evans",      age: "30"},
  {name: "Turner",     age: "31"},
  {name: "Torres",     age: "46"},
  {name: "Parker",     age: "34"},
  {name: "Collins",    age: "33"},
  {name: "Edwards",    age: "17"},
  {name: "Stewart",    age: "25"},
  {name: "Flores",     age: "40"},
  {name: "Morris",     age: "37"},
  {name: "Nguyen",     age: "26"},
  {name: "Murphy",     age: "38"},
  {name: "Rivera",     age: "24"},
  {name: "Cook",       age: "22"},
  {name: "Rogers",     age: "43"},
  {name: "Morgan",     age: "33"},
  {name: "Peterson",   age: "35"},
  {name: "Cooper",     age: "24"},
  {name: "Reed",       age: "17"},
  {name: "Bailey",     age: "34"},
  {name: "Bell",       age: "17"},
  {name: "Gomez",      age: "35"},
  {name: "Kelly",      age: "54"},
  {name: "Howard",     age: "30"},
  {name: "Ward",       age: "15"},
  {name: "Cox",        age: "45"},
  {name: "Diaz",       age: "20"},
  {name: "Richardson", age: "41"},
  {name: "Wood",       age: "40"},
  {name: "Watson",     age: "49"},
  {name: "Brooks",     age: "24"},
  {name: "Bennett",    age: "23"},
  {name: "Gray",       age: "7"},
  {name: "James",      age: "31"},
  {name: "Reyes",      age: "34"},
  {name: "Cruz",       age: "61"},
  {name: "Hughes",     age: "16"},
  {name: "Price",      age: "37"},
  {name: "Myers",      age: "46"},
  {name: "Long",       age: "53"},
  {name: "Foster",     age: "21"},
  {name: "Sanders",    age: "12"},
  {name: "Ross",       age: "54"},
  {name: "Morales",    age: "40"},
  {name: "Powell",     age: "39"},
  {name: "Sullivan",   age: "37"},
  {name: "Russell",    age: "17"},
  {name: "Ortiz",      age: "45"},
  {name: "Jenkins",    age: "50"},
  {name: "Gutierrez",  age: "27"},
  {name: "Perry",      age: "41"},
  {name: "Butler",     age: "38"},
  {name: "Barnes",     age: "11"},
  {name: "Fisher",     age: "32"},
];

export function setup(db, callback) {
  db.CreateTable('person')
  .add('id SERIAL PRIMARY KEY', 'name TEXT', 'age INTEGER')
  .executePromise()
  .then(() => {
    let promises = persons.map(person => {
      return db.Insert('person').set(person).executePromise();
    });
    return Promise.all(promises);
  })
  .then(() => callback(), reason => callback(reason));
}

export function teardown(db, callback) {
  db.executeSQL('DROP TABLE person', [], callback);
}
